#!/bin/bash -e

USAGE="Usage: $0 URL DIR [CHECK_FILE] [SSH_DIR] [SSH_ENV]"
URL="${1:?$USAGE}"
DIR="${2:?$USAGE}"
CHECK_FILE=${3:-README.md}
SSH_DIR=${4:-$HOME/.ssh}
SSH_ENV=${5:-$SSH_DIR/environment}

ssh_start_agent() {
	echo -n "Initialising new SSH agent... "
	ssh-agent | sed 's/^echo/#echo/' > "$SSH_ENV"
	echo "Done."
	chmod 600 "$SSH_ENV"
	. "$SSH_ENV" > /dev/null
}

if [ -e "$SSH_DIR/passphrase" ]; then
	if [ -f "$SSH_ENV" ]; then
		. "$SSH_ENV" > /dev/null
		ps -ef | grep ${SSH_AGENT_PID} \
			| grep ssh-agent$ > /dev/null || ssh_start_agent
	else
		ssh_start_agent
	fi
	cat $SSH_DIR/passphrase \
		| SSH_ASKPASS=/bin/cat setsid -w ssh-add $SSH_DIR/id_rsa \
		> /dev/null 2>&1
fi

if [ -e "$DIR/$CHECK_FILE" ]; then
	echo "Refreshing $DIR..."
	/usr/bin/git -C $DIR pull --ff-only
else
	if /usr/bin/git clone $URL $DIR; then
		echo "Cloned $DIR repository."
	else
		echo "Error cloning $DIR repository."
		exit 1
	fi
fi
